project:
  type: website
  output-dir: docs
  

languages:
  default: en
  additional:
    - id: ja
      title: 日本語
      url: /ja/
      output-dir: "ja"

website:
  back-to-top-navigation: true
  image: "images/network.jpg"
  navbar:
    pinned: true
    collapse: false
    left:
      - text: Home
        href: index.qmd        
      - text: About
        href: About/about.qmd       
      - text: Publications
        href: Publications/index.qmd
      - text: Documents
        menu:
          - text: R
            href: Documents/R/index.qmd
          - text: papers

    right: 
      - icon: github
        href: 'https://github.com/hiroakif93'
  
  sidebar:
    - title: "R"
      style: "docked"
      background: light
      contents:
        - Documents/R/index.qmd
        - Documents/R/01_aboutR.qmd
        - Documents/R/02_Class.qmd

  page-footer:
    center: "Copyright 2021, Hiroaki Fujita"
    border: true
    background: transparent

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



