project:
  type: website
  output-dir: docs

website:
  title: "Hiroaki Fujita's website"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: Profile/about.qmd
        text: Profile
      - text: Documents

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



