project:
  type: website
  output-dir: docs
  

languages:
  default: en
  additional:
    - id: ja
      title: 日本語
      url: /ja/
      output-dir: "ja"

website:
  back-to-top-navigation: true

  navbar:
    pinned: true
    collapse: false
    left:
      - text: Home
        href: index.qmd        
      - text: About
        href: About/about.qmd       
      - text: Publications
        href: Publications/index.qmd
      - text: Documents
        menu:
          - text: R
          - text: papers
          
    right: 
      - icon: github
        href: 'https://github.com/hiroakif93'
  
  page-footer:
    center: "Copyright 2021, Hiroaki Fujita"
    border: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



