project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

languages:
  default: en
  additional:
    - id: ja
      title: 日本語
      url: /ja/
      output-dir: "ja"

website:
  navbar:
    pinned: true
    collapse: false
    left:
      - text: Home
        href: index.qmd        
      - text: About
        href: About/about.qmd       
      - text: Publications
        href: Publications/index.qmd
      - text: Documents
        menu:
          - text: R
          - text: papers

footer:
  "© 2024 Hiroaki Fujita"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



